### ISSUE TITLE
Dark Theme toggle

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/Flutter-Blog-App#12]

**Comment by arbazdiwan** [comment]
I will do this @himanshusharma89.
Please assign the task to me.

**Comment by himanshusharma89** [comment]
Okay @arbazdiwan, assigning it to you. Create the toggle in the Drawer.

**Comment by daruanugerah** [comment]
are you want add dark mode with toogle button? has this issue been worked out?

**Comment by himanshusharma89** [comment]
@daruanugerah This issue is assigned to @arbazdiwan. And @arbazdiwan If you are facing an issue or cannot create a PR, comment here, I'll assign it to @daruanugerah. Also @daruanugerah you can create issues if you find some error or you want a feature in this project.

**Comment by arbazdiwan** [comment]
I am working on it. will open a PR tomorrow.

**Comment by arbazdiwan** [comment]
ok

**Comment by arbazdiwan** [comment]
Hello @himanshusharma89 ,

I have created PR.

I just went through the app to test the functionality. The add post functionality does not seem to be working.

However, I haven't touched anything (in existing functionality) except adding the toggle-darkmode functionality.

Looking forward to working with you more.

Thanking you,
Arbaz Diwan

**Comment by arbazdiwan** [comment]
I resolved all the conflicts. waiting for your review @himanshusharma89

**Comment by arbazdiwan** [comment]
I resolved all the conflicts. waiting for your review @himanshusharma89

**Comment by himanshusharma89** [comment]
> Hello @himanshusharma89 , I have created PR. I just went through the app to test the functionality. The add post functionality does not seem to be working. However, I haven't touched anything (in existing functionality) except adding the toggle-darkmode functionality. Looking forward to working with you more. Thanking you, Arbaz Diwan

You can create an issue and work on it. ANd I have updated your PR have a look into it.
