### ISSUE TITLE
Deploy APK GitHub Action

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/Flutter-Blog-App#14]
A GitHub Action to build the release APK whenever a PR is merged or code is pushed.

**Comment by Wizpna** [comment]
Please, can you give more insight regarding this issue.

**Comment by himanshusharma89** [comment]
@Wizpna Check the description, it is updated now.

**Comment by Mrgove10** [comment]
i'm on this

**Comment by Wizpna** [comment]
I have submitted a pull request regarding this issue, please review and merge

**Comment by himanshusharma89** [comment]
Hey @Mrgove10, you can take up another issue or create a new one if you find it valid for this project.

**Comment by Wizpna** [comment]
I have re-submitted another pull request regarding this issue, please review and merge

**Comment by Mrgove10** [comment]
**PR #21 Will not work!**

I have done the test, the action crashes.
You took the first tutorial on github and copy pasted it (see https://github.com/marketplace/actions/flutter-action). Please at least read the original issue description and adapt it to the project.

@himanshusharma89 May i do a pr of my tested version that actualy works ?!

PS: we are all here for the hacktoberfest, it is not a reason to push bad code that does not work !

edit : typos

**Comment by himanshusharma89** [comment]
Sure @Mrgove10 Go ahead
