### ISSUE TITLE
Fade Transition Between Screens

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/Flutter-Blog-App#28]

**Comment by AyushRajSharma** [comment]
faded transition between screen means when we change screen from one to another it will fade out and fade in with another screen?
i wanna take it, please assign me

**Comment by himanshusharma89** [comment]
Yeah, @AyushRajSharma. Assigning it to you.

**Comment by AyushRajSharma** [comment]
![image](https://user-images.githubusercontent.com/58889205/95340606-fca8b000-08d2-11eb-90ef-f8807a3c9c13.png)
i want jetbrains license or activation key or activated jetbrains credentials for markdown navigator in existing app to get all dependencies install in android studio,
please help me,
thanks.

**Comment by himanshusharma89** [comment]
@AyushRajSharma There is no need for this plugin for this issue. Check this for fade transition: https://medium.com/flutter-community/everything-you-need-to-know-about-flutter-page-route-transition-9ef5c1b32823

**Comment by AyushRajSharma** [comment]
Ok I will make PR soon.

**Comment by himanshusharma89** [comment]
@AyushRajSharma Any update?

**Comment by AyushRajSharma** [comment]
![flutter-Blog-App](https://user-images.githubusercontent.com/58889205/95858468-c78cd980-0d7a-11eb-80fb-3b146391cbb9.gif)
i have created this gif with 2 sec duration of screen transition to see the animation.
i hope you want like this.

**Comment by AyushRajSharma** [comment]
we can also use other type of animation like  
  fade,
  rightToLeft,
  leftToRight,
  upToDown,
  downToUp,
  scale,
  rotate,
  size,
  rightToLeftWithFade,
  leftToRightWithFade
by single change of pageTransitionType.
i hope this will close the issue,
thanks

**Comment by Saransh-cpp** [comment]
Hey, can I work on this issue if no one is working on it already?

**Comment by himanshusharma89** [comment]
Sure, @Saransh-cpp
