### ISSUE TITLE
Medium Article Fetching logic

### ISSUE THREAD

**Issue by shubham-chhimpa** [himanshusharma89/Flutter-Blog-App#29]
write the logic to fetch medium article by username using the rss2json api

```
https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/@username
```

**Comment by shubham-chhimpa** [comment]
I have created a pull request regarding this issue

**Comment by himanshusharma89** [comment]
@all-contributors please add @shubham-chhimpa for code
