### ISSUE TITLE
App Logo Update

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/Flutter-Blog-App#32]
Update the current logo of the app with something new.

**Comment by mayankparida** [comment]
Please could you assign me this issue to solve. Also please do provide the logo to be updated. Thank you.

**Comment by himanshusharma89** [comment]
@mayankparida Here is the logo: https://github.com/himanshusharma89/Flutter-Blog-App/blob/master/assets/blogging.png

**Comment by himanshusharma89** [comment]
@mayankparida Any update?

**Comment by mayankparida** [comment]
I'm really sorry... I'm not good at designing logos. Thank you for considering me. It means a lot.

**Comment by himanshusharma89** [comment]
okay @mayankparida

**Comment by meetxpress** [comment]
what kind of logo do you need? It would be better is you suggest any name so that the scope of designing will narrow down.

**Comment by himanshusharma89** [comment]
@meetxpress The logo can be something like the initial of the app: "B" or something else if you have it in the mind

**Comment by meetxpress** [comment]
How to submit the logo as a contribution?

**Comment by enzoftware** [comment]
@himanshusharma89  You like something like this?
![FLUTTER_BLOG](https://user-images.githubusercontent.com/22333076/95803636-39571b80-0cc6-11eb-9881-2cfba8bfc7a8.png)

**Comment by himanshusharma89** [comment]
Yeah @enzoftware, this looks good. You can create png logos but also create a logo for dark mode

**Comment by enzoftware** [comment]
Could you assign this to me? I remove the background and made another for dark mode.

**Comment by himanshusharma89** [comment]
Yeah sure @enzoftware. You are assigned.

**Comment by himanshusharma89** [comment]
Hi @enzoftware, any update?

**Comment by enzoftware** [comment]
Yes! Here is my update 😸 
### Dark theme logo
- Probably this could be a sky-blue variation or it's ok in white?

![flutter_blog_dark](https://user-images.githubusercontent.com/22333076/96025933-75e85b80-0e1b-11eb-924b-0503871499f5.png)



### Light theme logo
![flutter_blog_light](https://user-images.githubusercontent.com/22333076/96025943-7a147900-0e1b-11eb-897d-09287feb724e.png)

Waiting for feedback 👍

**Comment by himanshusharma89** [comment]
@enzoftware This looks perfect! Create a PR for this and add a blue one also in the PR. I hope these logos are not claimed by someone else. And can you also add the SVGs in the PR?

**Comment by himanshusharma89** [comment]
@enzoftware Any update?

**Comment by enzoftware** [comment]
Hi @himanshusharma89, sorry for the delay in my response. I have been submitting the PR today. Thanks
