### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/Flutter-Blog-App#33]
Improve the current About Page and add the following: 

- [x] Description of the app

- [x] Tech Stack Used

- [x] Platforms Available

- [x] Developer: Himanshu Sharma

- [x] Contributors: All the contributors of the app

**Comment by dmb1107** [comment]
May I be assigned to this?

**Comment by himanshusharma89** [comment]
Sure @dmb1107

**Comment by Janhavi23** [comment]
Hey! Can I work on this?

**Comment by himanshusharma89** [comment]
Hello @Janhavi23, this issue is currently assigned to @dmb1107, you can contribute to other issues or create one of your own if you find it good for this project. And @dmb1107 any update? facing issues or something?

**Comment by Janhavi23** [comment]
@himanshusharma89 I will try to work on some other issue . Thank you.

**Comment by dmb1107** [comment]
> Hello @Janhavi23, this issue is currently assigned to @dmb1107, you can contribute to other issues or create one of your own if you find it good for this project. And @dmb1107 any update? facing issues or something?

I've been struggling to get Flutter installed properly on my computer. You can assign it to @Janhavi23 instead.

**Comment by himanshusharma89** [comment]
Okay @dmb1107, but if you need some help, let me know. @Janhavi23 Assigning this to you.

**Comment by Janhavi23** [comment]
@himanshusharma89 Thank you.

**Comment by Janhavi23** [comment]
@himanshusharma89  an image flutter_dev.png is missing from the assets folder . It is actually used in the About page. Can you tell me what that image is supposed to be?

**Comment by himanshusharma89** [comment]
@Janhavi23 I guess it was accidentally added to the .gitignore file. No issues, it is not needed because we need to change the UI of the page and also you can add a new image if you want.

**Comment by Janhavi23** [comment]
@himanshusharma89 what should be present in the platforms available?

**Comment by himanshusharma89** [comment]
@Janhavi23 Android and iOS(incoming) something like this

**Comment by Janhavi23** [comment]
@himanshusharma89 Ok got it , also how do I get the details of the contributors of the app?

**Comment by himanshusharma89** [comment]
@Janhavi23 Check the section below about of the repo

**Comment by Janhavi23** [comment]
@himanshusharma89  I just have to mention the names of the contributors right?

**Comment by himanshusharma89** [comment]
@Janhavi23 Yes, just map a list, I'll make it dynamic later on.

**Comment by Janhavi23** [comment]
@himanshusharma89 I am done with the about Page.Should I send a screenshot before making a PR?

**Comment by himanshusharma89** [comment]
@Janhavi23, first of all, pull the latest changes after committing your work. And then create a PR, attach the screenshot in that PR.

**Comment by Janhavi23** [comment]
@himanshusharma89 I have created a PR. Please do let me know if anything needs to be changed or improved.

**Comment by meetxpress** [comment]
It would be better if you share more information about your requirements.

**Comment by himanshusharma89** [comment]
@meetxpress Information is already provided and I am working on it currently.
