### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/Flutter-Blog-App#4]
- [x] License Section

- [x] Code of Conduct Section

- [x] Contributing Section

- [x] App Mockups by https://threed.io/

- [x] Contributors

**Comment by dramikei** [comment]
What changes do you want?

**Comment by himanshusharma89** [comment]
@dramikei Check the description

**Comment by yash2189** [comment]
Hi can I work on this if it's available?

**Comment by himanshusharma89** [comment]
@yash2189 Sure you can work on it, but do include as much useful info as you can otherwise it'll be invalid for Hacktoberfest

**Comment by yash2189** [comment]
Sure @himanshusharma89

**Comment by yash2189** [comment]
@himanshusharma89 is it fine if I add a table of content section and arrange the existing contents accordingly with the changes that are mentioned in the description?

**Comment by himanshusharma89** [comment]
Yeah, go-ahead @yash2189

**Comment by yash2189** [comment]
@himanshusharma89 since there is already a `code of conduct` file . Do I just need to reference it from `README.md`?

**Comment by himanshusharma89** [comment]
Yes @yash2189 Or try to embed it

**Comment by himanshusharma89** [comment]
@yash2189 Any update? I have updated the description

**Comment by yash2189** [comment]
@himanshusharma89 sorry for being inactive I have almost completed it ... is it fine if I raise a PR till tomorrow since I have my term exams on?

**Comment by himanshusharma89** [comment]
Sure, no issues @yash2189

**Comment by yash2189** [comment]
@himanshusharma89 I need to replace the app screen by the mockups right?

**Comment by himanshusharma89** [comment]
@yash2189 Left the mockups part to me. It needs iOS screenshots

**Comment by yash2189** [comment]
@himanshusharma89  I have completed everything except for the contributors section. What is to be added to the same?

**Comment by himanshusharma89** [comment]
@yash2189 No need for adding it, I have taken care of it, and pull the latest code and alter your changes accordingly.

**Comment by yash2189** [comment]
@himanshusharma89  I have made a PR but it shows there are some conflicts

**Comment by himanshusharma89** [comment]
@yash2189 That is why you need to pull the latest code from my branch

**Comment by yash2189** [comment]
yes got it

**Comment by yash2189** [comment]
@himanshusharma89  Can you please review my PR #49 ?

**Comment by yash2189** [comment]
@himanshusharma89 Does my name count as a contributor or is it only for those who have contributed for code and design?

**Comment by himanshusharma89** [comment]
You are added @yash2189 as a contributor.

**Comment by Saransh-cpp** [comment]
Hey, can I work on the app mockups section?

**Comment by himanshusharma89** [comment]
Sure @Saransh-cpp, assigning it to you.

**Comment by Saransh-cpp** [comment]
Thanks, should I use the blogs already written or should I write some dummy blogs having 1-2 lines of Lorem and capture those?

**Comment by himanshusharma89** [comment]
You can create some dummy blogs @Saransh-cpp

**Comment by Saransh-cpp** [comment]
Hey, do the mockups necessarily need iOS screenshots?

**Comment by himanshusharma89** [comment]
Not necessarily, you can add other mockups also.

**Comment by Saransh-cpp** [comment]
Can you have a look at the forked repository as I have added the mockups ( let me know if you want any kind of changes ) or should I just generate a PR directly?

**Comment by himanshusharma89** [comment]
@Saransh-cpp You should create a PR.
