### ISSUE TITLE
Section to Display Medium Articles

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/Flutter-Blog-App#5]

**Comment by shubham-chhimpa** [comment]
@himanshusharma89  We can display medium articles using the new webview package by flutter

https://pub.dev/packages/webview_flutter

**Comment by himanshusharma89** [comment]
@shubham-chhimpa Yeah, that is one way or we can just use a Medium get API to get articles of a particular user. What do you think will be good approach?

**Comment by masterashu** [comment]
I don't think Medium has APIs for to get posts/articles.
[Here](https://github.com/Medium/medium-api-docs#33-posts) is the list of APIs.
It seems only POST (Creating a new item) APIs are available.

**Comment by himanshusharma89** [comment]
@masterashu Check this: https://stackoverflow.com/a/39646796/11545939, I used it and it works.
