### ISSUE TITLE
The current Dart SDK version is 2.9.0.

### ISSUE THREAD

**Issue by vipuluthaiah** [himanshusharma89/Flutter-Blog-App#59]
The current Dart SDK version is 2.9.0.

Because blog_app requires SDK version >=1.22.0 <2.0.0, version solving failed.
Running "flutter pub get" in Flutter-Blog-App...
pub get failed (1; Because blog_app requires SDK version >=1.22.0 <2.0.0, version solving failed.)

**Comment by himanshusharma89** [comment]
This issue is resolved in the recent update.
