### ISSUE TITLE
UI Update of PostView 

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/Flutter-Blog-App#6]
- [x] Make App Bar transparent

- [x] Change back icon to something like ios_back

- [x] Add more UI adjustments that you prefer

**Comment by Promise4235** [comment]
How do you want the post view UI to be updated

**Comment by himanshusharma89** [comment]
@Promise4235 Check the description now, it is updated.

**Comment by Wizpna** [comment]
Can you assign this PR to me

**Comment by himanshusharma89** [comment]
@Wizpna I'll assign it to you, but don't create commits from a different account.

**Comment by Wizpna** [comment]
Ok, thanks

**Comment by Wizpna** [comment]
I have submitted a pull request regarding this issue, please review and merge

**Comment by himanshusharma89** [comment]
@Wizpna Check out the comment in the PR

**Comment by Wizpna** [comment]
ok

**Comment by Wizpna** [comment]
Please can you throw more light on what you mean

**Comment by Wizpna** [comment]
I have fixed the issue, check out my new pull request

**Comment by yash2189** [comment]
Hello, can I work on this?

**Comment by himanshusharma89** [comment]
@yash2189 I am going to push some changes and update the description after that you can work on it
