### ISSUE TITLE
Text written in the TextFormField in the medium_articles.dart page is not visible in the light mode 

### ISSUE THREAD

**Issue by Saransh-cpp** [himanshusharma89/Flutter-Blog-App#61]
For example -

![Screenshot_1611644132](https://user-images.githubusercontent.com/74055102/105810846-aa9ab000-5fd1-11eb-8a2b-6b27c20f93fb.png)

**Comment by Saransh-cpp** [comment]
A simple fix would be to change the color of the text to something that is visible in both light and dark mode, if this is what you want then I can fix this.

**Comment by himanshusharma89** [comment]
Sure, go ahead.
