### ISSUE TITLE
UI Update of Create Post

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/Flutter-Blog-App#7]
- [x] Make App Bar transparent

- [x] Change back icon to something like ios_back

- [x] Increase the height of the Post Body text field

- [x] Add more UI adjustments that you prefer

**Comment by aditijhaa9901** [comment]
i would like to work on this issue.

**Comment by himanshusharma89** [comment]
Hey @aditijhaa9901, check the description it is updated now.

**Comment by daruanugerah** [comment]
I will work on this problem. Do you want to make the appbar transparent only for create post?

**Comment by Wizpna** [comment]
I have submitted a pull request regarding this issue, please review and merge

**Comment by daruanugerah** [comment]
i have change appbar style to transparent and icon back to icon back ios in add_post.dart
please review and merge

**Comment by himanshusharma89** [comment]
Okay so we have PR from both of you, so what can we do is, I'll merge the one by @daruanugerah after review and I'll update the issue description if anything is not included then @Wizpna can create a new PR as his current PR consists commit from a different account. Does this work with both of you?

**Comment by daruanugerah** [comment]
@himanshusharma89 okay
